twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        app_url_api: "%env(URL_API)%"



when@test:
    twig:
        strict_variables: true
