<?php

namespace ContainerESHDRE6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCityService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.RKHPBmO.App\Entity\City' shared service.
     *
     * @return \App\Entity\City
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.RKHPBmO": it references class "App\\Entity\\City" but no such service exists.');
    }
}
