<?php

namespace ContainerESHDRE6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLocationTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\LocationType' shared autowired service.
     *
     * @return \App\Form\LocationType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/LocationType.php';

        return $container->privates['App\\Form\\LocationType'] = new \App\Form\LocationType();
    }
}
