<?php

namespace ContainerESHDRE6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStatusServicesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\StatusServices' shared autowired service.
     *
     * @return \App\Service\StatusServices
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/StatusServices.php';
        include_once \dirname(__DIR__, 4).'/src/Command/AutoStatusCommands.php';

        return $container->privates['App\\Service\\StatusServices'] = new \App\Service\StatusServices(new \App\Command\AutoStatusCommands(($container->privates['App\\Repository\\EventRepository'] ?? $container->load('getEventRepositoryService')), ($container->privates['App\\Repository\\StatusRepository'] ?? $container->load('getStatusRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService())));
    }
}
