<?php

namespace ContainerRNhGaL0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__HMQm8kService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..hMQm8k' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..hMQm8k'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'event' => ['privates', '.errored..service_locator..hMQm8k.App\\Entity\\Event', NULL, 'Cannot autowire service ".service_locator..hMQm8k": it references class "App\\Entity\\Event" but no such service exists.'],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'event' => 'App\\Entity\\Event',
            'manager' => '?',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
