<?php

namespace ContainerRNhGaL0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZXyCReuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zXyCReu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zXyCReu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'event' => ['privates', '.errored..service_locator.zXyCReu.App\\Entity\\Event', NULL, 'Cannot autowire service ".service_locator.zXyCReu": it references class "App\\Entity\\Event" but no such service exists.'],
            'mailService' => ['privates', 'App\\Service\\MailService', 'getMailServiceService', true],
        ], [
            'event' => 'App\\Entity\\Event',
            'mailService' => 'App\\Service\\MailService',
        ]);
    }
}
