<?php

namespace ContainerRNhGaL0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Lc7al7FService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lc7al7F' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lc7al7F'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'location' => ['privates', '.errored..service_locator.lc7al7F.App\\Entity\\Location', NULL, 'Cannot autowire service ".service_locator.lc7al7F": it references class "App\\Entity\\Location" but no such service exists.'],
        ], [
            'location' => 'App\\Entity\\Location',
        ]);
    }
}
