<?php

namespace ContainerRNhGaL0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6ltfT6PService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6ltfT6P' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6ltfT6P'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'event' => ['privates', '.errored..service_locator.6ltfT6P.App\\Entity\\Event', NULL, 'Cannot autowire service ".service_locator.6ltfT6P": it references class "App\\Entity\\Event" but no such service exists.'],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'statusRepository' => ['privates', 'App\\Repository\\StatusRepository', 'getStatusRepositoryService', true],
        ], [
            'event' => 'App\\Entity\\Event',
            'manager' => '?',
            'statusRepository' => 'App\\Repository\\StatusRepository',
        ]);
    }
}
