<?php

namespace ContainerRNhGaL0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TKVotFBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TKVotFB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TKVotFB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'eventRepository' => ['privates', 'App\\Repository\\EventRepository', 'getEventRepositoryService', true],
            'services' => ['privates', 'App\\Service\\StatusServices', 'getStatusServicesService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'eventRepository' => 'App\\Repository\\EventRepository',
            'services' => 'App\\Service\\StatusServices',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
