<?php

namespace ContainerRNhGaL0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEvent5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.vHF6vzr.App\Entity\Event' shared service.
     *
     * @return \App\Entity\Event
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.vHF6vzr": it references class "App\\Entity\\Event" but no such service exists.');
    }
}
