<?php

namespace ContainerRNhGaL0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\EventService' shared autowired service.
     *
     * @return \App\Service\EventService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/EventService.php';

        return $container->privates['App\\Service\\EventService'] = new \App\Service\EventService(($container->privates['App\\Repository\\StatusRepository'] ?? $container->load('getStatusRepositoryService')), ($container->privates['App\\Repository\\LocationRepository'] ?? $container->load('getLocationRepositoryService')));
    }
}
