<?php

namespace ContainerRNhGaL0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportUsersCSVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ImportUsersCSV' shared autowired service.
     *
     * @return \App\Command\ImportUsersCSV
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/ImportUsersCSV.php';

        $container->privates['App\\Command\\ImportUsersCSV'] = $instance = new \App\Command\ImportUsersCSV(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), (\dirname(__DIR__, 4).'/public/ImportCSV/'), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->privates['App\\Repository\\CampusRepository'] ?? $container->load('getCampusRepositoryService')), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')));

        $instance->setName('app:create-user');
        $instance->setDescription('Création d\'utilisateurs à partir d\'un fichier CSV.');

        return $instance;
    }
}
