<?php

namespace ContainerRNhGaL0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLocationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.lc7al7F.App\Entity\Location' shared service.
     *
     * @return \App\Entity\Location
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.lc7al7F": it references class "App\\Entity\\Location" but no such service exists.');
    }
}
