<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.53a95366.js',
                '/build/409.9aceef6e.js',
                '/build/633.bc547f46.js',
                '/build/0.f0cb8a30.js',
                '/build/566.198ffb11.js',
                '/build/app.a62760b0.js',
            ],
            'css' => [
                '/build/app.73bda801.css',
            ],
        ],
        'event' => [
            'js' => [
                '/build/runtime.53a95366.js',
                '/build/409.9aceef6e.js',
                '/build/event.520336e4.js',
            ],
        ],
        'filterCheckbox' => [
            'js' => [
                '/build/runtime.53a95366.js',
                '/build/filterCheckbox.69b10654.js',
            ],
        ],
        'detail' => [
            'js' => [
                '/build/runtime.53a95366.js',
                '/build/409.9aceef6e.js',
                '/build/0.f0cb8a30.js',
                '/build/detail.93c64970.js',
            ],
        ],
        'map' => [
            'js' => [
                '/build/runtime.53a95366.js',
                '/build/633.bc547f46.js',
                '/build/map.5c8a0e40.js',
            ],
        ],
    ],
],

]];
